CREATE TABLE shows (
show_id SERIAL PRIMARY KEY,
title VARCHAR(255),
venue VARCHAR(255),
event_date DATE,
city VARCHAR(255),
url VARCHAR(255),
end_date TIMESTAMP,
start_date TIMESTAMP,
completedevent BOOLEAN DEFAULT(FALSE),
);

ALTER TABLE shows ADD COLUMN image_url VARCHAR(255);
ADD COLUMN categories VARCHAR(255)[],
ADD COLUMN instagram VARCHAR(255),
ADD COLUMN web VARCHAR(255),
ADD COLUMN address VARCHAR(255);

ALTER TABLE shows 
  ADD COLUMN is_featured BOOLEAN DEFAULT FALSE,
  ADD COLUMN youtube VARCHAR(255),
  ADD COLUMN description TEXT;